export const ForgetTokenMock =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzM0MTEyNjMzLCJleHAiOjE3MzQxMTQ0MzMsImF1ZCI6InVzZXJzIiwiaXNzIjoiZm9yZ2V0Iiwic3ViIjoiMiJ9.F0VubfFkRk_Jiq928MdQgINcluQy_2rid-oqGYrB3CM';
